# DO NOT MODIFY -- auto-generated by Apache Cordova

platform :ios, '13.0'

target 'WebToNative' do
	project 'WebToNative.xcodeproj'
	post_install do |installer|
		installer.pods_project.build_configurations.each do |config|
		  config.build_settings["EXCLUDED_ARCHS[sdk=iphonesimulator*]"] = "arm64"
		end
	end
	post_install do |installer|
		installer.pods_project.targets.each do |target|
		  target.build_configurations.each do |config|
			config.build_settings['ONLY_ACTIVE_ARCH'] = 'YES'
		  end
		end
	  end
	# luc dau chi co z thoi
end
